apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2026-05-11T07:04:10Z"
  name: dev-sa
  namespace: exercise-04
  resourceVersion: "1298516"
  uid: a9fcdf4f-e4de-445a-9f69-9efd9cbb981c
